"""Add tags column to Template table

Revision ID: 2eda6c2229ef
Revises: 7774324d1447
Create Date: 2025-07-20 20:09:38.289458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eda6c2229ef'
down_revision: Union[str, Sequence[str], None] = '7774324d1447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('tags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'tags')
    # ### end Alembic commands ###
