from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import io

def create_pdf_worksheet(all_sections_and_problems_data, overall_include_answer_key):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            rightMargin=0.5*inch, leftMargin=0.5*inch,
                            topMargin=1.2*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    story = []

    all_problems_for_answer_key = []
    
    def my_header_footer(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica-Bold', 10)
        canvas.drawString(0.5*inch, 10.5*inch, "TEACHER'S PET")
        
        canvas.setFont('Helvetica', 12)
        canvas.drawString(4.5*inch, 10.5*inch, "Name: ________________________")
        canvas.drawString(4.5*inch, 10.2*inch, "Date:  ________________________")
        
        canvas.setFont('Helvetica-Oblique', 8)
        canvas.drawCentredString(4.25*inch, 0.5*inch, f"Page {doc.page} - Generated by Teacher's Pet")
        canvas.restoreState()

    def make_vertical_problem(item, number):
        # FIX: Ensure we handle cases where item might accidentally be a string
        if isinstance(item, str):
            return Paragraph(f"{number}. {item}", styles['Normal'])

        num1 = item.get('num1')
        num2 = item.get('num2')
        symbol = item.get('symbol', '+')

        if num1 is None or num2 is None:
            return Paragraph(f"{number}. {item.get('question', '')}", styles['Normal'])

        def format_val(v):
            return str(int(v)) if isinstance(v, float) and v.is_integer() else str(v)

        data = [
            [f"{number}.", format_val(num1)],
            [symbol, format_val(num2)]
        ]

        t = Table(data, colWidths=[0.3*inch, 0.8*inch])
        t.setStyle(TableStyle([
            ('ALIGN', (1, 0), (1, 1), 'RIGHT'),
            ('FONTNAME', (1, 0), (1, 1), 'Courier-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 14),
            ('LINEBELOW', (1, 1), (1, 1), 1.5, colors.black),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
        ]))
        
        return t

    current_row = []
    problems_per_row = 3
    is_first_section = True
    problem_counter = 0 

    for item in all_sections_and_problems_data:
        # Extra safety check for dictionary types
        if not isinstance(item, dict):
            continue

        if item.get("type") == "section_header":
            if current_row:
                story.append(Table([current_row], colWidths=[2.3*inch]*3))
                current_row = []

            if not is_first_section: 
                story.append(PageBreak())
            
            is_first_section = False
            story.append(Paragraph(f"{item.get('subject')} - {item.get('topic_name')}", styles['h1']))
            story.append(Spacer(1, 0.3 * inch))
        else:
            problem_counter += 1
            all_problems_for_answer_key.append(item)
            
            # FIX: Pass the entire 'item' dictionary, not just 'item[question]'
            p_widget = make_vertical_problem(item, problem_counter)
            current_row.append(p_widget)

            if len(current_row) == problems_per_row:
                story.append(Table([current_row], colWidths=[2.3*inch]*3))
                story.append(Spacer(1, 0.2*inch))
                current_row = []

    # Handle remaining problems in the last row
    if current_row:
        while len(current_row) < problems_per_row:
            current_row.append(Paragraph("", styles['Normal']))
        story.append(Table([current_row], colWidths=[2.3*inch]*3))

    if overall_include_answer_key and all_problems_for_answer_key:
        story.append(PageBreak())
        story.append(Paragraph("Answer Key", styles['h2']))
        
        # Grid-based answer key for better space usage
        answer_data = []
        current_ans_row = []
        for i, p in enumerate(all_problems_for_answer_key):
            current_ans_row.append(f"{i+1}. {p.get('answer', 'N/A')}")
            if len(current_ans_row) == 5:
                answer_data.append(current_ans_row)
                current_ans_row = []
        if current_ans_row:
            while len(current_ans_row) < 5: current_ans_row.append("")
            answer_data.append(current_ans_row)
            
        story.append(Table(answer_data, colWidths=[1.5*inch]*5))

    doc.build(story, onFirstPage=my_header_footer, onLaterPages=my_header_footer)
    buffer.seek(0)
    return buffer